### ISSUE TITLE
INSERT INTO ... VALUE support

### ISSUE THREAD

**Issue by TuomasKiviaho** [burtcorp/athena-jdbc#11]
I am about to start with Athena and give a go to their fairly new [INSERT INTO ... VALUES](https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-athena-adds-support-inserting-data-into-table-results-of-select-query/) support.  

I skimmed the tests briefly and saw that INSERT INTO falls into not supported category. Is this something that would be considered worthwhile of having or even possible to be implemented.

https://github.com/burtcorp/athena-jdbc/blob/7ffb463d7e94d98cfe69f9e74d829e6c5bd5b363/src/test/java/io/burt/athena/AthenaStatementTest.java#L329

**Comment by iconara** [comment]
Hi, that sounds like a good contribution. When I wrote the driver I wasn't expecting the team to add that particular feature.

Is your plan to make the variant of `execute` you link to return [the update count](https://docs.aws.amazon.com/athena/latest/APIReference/API_GetQueryResults.html#athena-GetQueryResults-response-UpdateCount)?

**Comment by stenlarsson** [comment]
The driver in this repo is no longer maintained, please have a look at the official [Amazon Athena JDBC driver v3](https://docs.aws.amazon.com/athena/latest/ug/jdbc-v3-driver.html) instead.
