### ISSUE TITLE
Question: does the connection using JDBC must be async?

### ISSUE THREAD

**Issue by RFayez** [burtcorp/athena-jdbc#26]
I understand with sdk client when we call startqueryexecution the result is queryExecutionId that can be used to check later on query result , is my understanding correct?
If yes , can this be done using JDBC connection to athena?

**Comment by iconara** [comment]
The most common use case for this JDBC drive is to use the JDBC API to run a query and get the results as one operation. JDBC is a synchronous API and this driver makes interaction with Athena synchronous even though the Athena API is asynchronous itself.

However, this driver also provides access to the execution ID, which means you can do a mix if synchronous and asynchronous if you want. See "Getting the query execution ID from a ResultSet" in the readme for an example.

**Comment by RFayez** [comment]
Thank you so much iconara for your quick feedback and help.

I have one more question, In the "Getting the query execution ID from a ResultSet" section, the resultSet will not return until the query is completely finalized, So query execution id in result set metadata will not be used for checking if the query execution is finished or not in such case. is my understanding correct?

**Comment by iconara** [comment]
Yeah, you're right, I misremembered the implementation. The `Statement#execute` call does not allow access to the execution ID before the result is available, so the mix of sync and async is not possible. The reason we added `ResultSet#getQueryExecutionId` was that we wanted access to statistics and metadata, which is only available after completion anyway.

If you need access to the execution ID while the query is running I think it would be an interesting feature to add. I think you could add a `AthenaStatement#executeAsync` that returns a subclass of `Future<ResultSet>` that would also have a property that provides access to the execution ID.

I don't have the bandwidth to work on anything like that right now, but I can write a spec if you want to take a stab at a PR.

**Comment by stenlarsson** [comment]
The driver in this repo is no longer maintained, please have a look at the official [Amazon Athena JDBC driver v3](https://docs.aws.amazon.com/athena/latest/ug/jdbc-v3-driver.html) instead.
